-- AVIATOR PREDICTOR - SHARED SUPABASE SCHEMA
-- This schema is intentionally namespaced with aviator_ to avoid touching
-- tables used by other projects in the same Supabase project.

create table if not exists public.aviator_users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null unique,
  current_package integer not null default 0 check (current_package between 0 and 3),
  cycle_no integer not null default 1 check (cycle_no > 0),
  payment_status text not null default 'pending',
  package1_status text not null default 'locked' check (package1_status in ('locked','pending','paid')),
  package2_status text not null default 'locked' check (package2_status in ('locked','pending','paid')),
  package3_status text not null default 'locked' check (package3_status in ('locked','pending','paid')),
  completed integer not null default 0 check (completed in (0,1)),
  last_page text not null default '/betting-site',
  last_login_at timestamptz,
  betting_site text,
  betting_site_image text,
  has_app_id boolean not null default false,
  app_id_code text,
  app_id_purchased_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.aviator_payments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.aviator_users(id) on delete cascade,
  package_no integer not null check (package_no between 1 and 3),
  amount integer not null check (amount > 0),
  payment_phone text not null,
  order_id text not null unique,
  reference text default '',
  transaction_id text default '',
  status text not null default 'pending' check (status in ('pending','paid','failed')),
  payment_status text not null default 'PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Safe migration for an existing shared Aviator table.
alter table public.aviator_users add column if not exists cycle_no integer not null default 1;
alter table public.aviator_users add column if not exists last_login_at timestamptz;

create index if not exists aviator_payments_user_id_idx on public.aviator_payments(user_id);
create index if not exists aviator_payments_status_idx on public.aviator_payments(status);
create index if not exists aviator_payments_order_id_idx on public.aviator_payments(order_id);

create table if not exists public.aviator_app_ids (
  id bigint generated by default as identity primary key,
  code text not null unique,
  user_id bigint not null references public.aviator_users(id) on delete cascade,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);

create table if not exists public.aviator_submissions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.aviator_users(id) on delete set null,
  full_name text not null,
  phone_number text not null,
  package text,
  package_no integer check (package_no between 1 and 3),
  amount integer,
  screenshot text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  app_id_generated text,
  timestamp timestamptz not null default now(),
  decision_date timestamptz
);

create index if not exists aviator_submissions_status_idx on public.aviator_submissions(status);
create index if not exists aviator_submissions_timestamp_idx on public.aviator_submissions(timestamp desc);

-- updated_at helper
create or replace function public.aviator_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists aviator_users_updated_at on public.aviator_users;
create trigger aviator_users_updated_at
before update on public.aviator_users
for each row execute function public.aviator_set_updated_at();

drop trigger if exists aviator_payments_updated_at on public.aviator_payments;
create trigger aviator_payments_updated_at
before update on public.aviator_payments
for each row execute function public.aviator_set_updated_at();

-- RLS is enabled because the same Supabase project is shared with other apps.
-- The Vercel API uses the publishable key, so the policies below allow only
-- the API's required operations on these namespaced tables.
alter table public.aviator_users enable row level security;
alter table public.aviator_payments enable row level security;
alter table public.aviator_app_ids enable row level security;
alter table public.aviator_submissions enable row level security;

drop policy if exists aviator_users_api_select on public.aviator_users;
create policy aviator_users_api_select on public.aviator_users for select to anon, authenticated using (true);

drop policy if exists aviator_users_api_insert on public.aviator_users;
create policy aviator_users_api_insert on public.aviator_users for insert to anon, authenticated with check (true);

drop policy if exists aviator_users_api_update on public.aviator_users;
create policy aviator_users_api_update on public.aviator_users for update to anon, authenticated using (true) with check (true);

drop policy if exists aviator_payments_api_select on public.aviator_payments;
create policy aviator_payments_api_select on public.aviator_payments for select to anon, authenticated using (true);

drop policy if exists aviator_payments_api_insert on public.aviator_payments;
create policy aviator_payments_api_insert on public.aviator_payments for insert to anon, authenticated with check (true);

drop policy if exists aviator_payments_api_update on public.aviator_payments;
create policy aviator_payments_api_update on public.aviator_payments for update to anon, authenticated using (true) with check (true);

drop policy if exists aviator_app_ids_api_select on public.aviator_app_ids;
create policy aviator_app_ids_api_select on public.aviator_app_ids for select to anon, authenticated using (true);

drop policy if exists aviator_app_ids_api_insert on public.aviator_app_ids;
create policy aviator_app_ids_api_insert on public.aviator_app_ids for insert to anon, authenticated with check (true);

drop policy if exists aviator_submissions_api_select on public.aviator_submissions;
create policy aviator_submissions_api_select on public.aviator_submissions for select to anon, authenticated using (true);

drop policy if exists aviator_submissions_api_insert on public.aviator_submissions;
create policy aviator_submissions_api_insert on public.aviator_submissions for insert to anon, authenticated with check (true);

drop policy if exists aviator_submissions_api_update on public.aviator_submissions;
create policy aviator_submissions_api_update on public.aviator_submissions for update to anon, authenticated using (true) with check (true);

create index if not exists aviator_payments_created_at_idx on public.aviator_payments(created_at desc);
